name: Test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        test: [
          tests/MongodbTest.php,
          tests/MysqlTest.php,
          tests/Postgresql12Test.php,
          tests/Postgresql13Test.php,
          tests/RedisTest.php
        ]
    steps:
      - uses: actions/checkout@v3
      - name: Composer install
        run: |
          composer install
      - name: Run tests
        run: |
          ./vendor/bin/phpunit ${{ matrix.test }}
