name: Test

on: push

jobs:

  test-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Composer install
        run: |
          composer install
      - name: PHPUnit
        run: |
          ./vendor/bin/phpunit

  test-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Composer install
        run: |
          composer install
      - name: PHPUnit
        run: |
          ./vendor/bin/phpunit
