name: Test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        test: [
          tests/Mongodb503Test.php,
          tests/Mongodb4410Test.php,
          tests/Mysql5731Test.php,
          tests/Mysql8030Test.php,
          tests/Postgresql124Test.php,
          tests/Postgresql132Test.php,
          tests/Redis626Test.php,
          tests/Redis6016Test.php,
          tests/Memcached1631Test.php
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Install PHP and Composer on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install php
          brew install composer
      - name: Install PHP and Composer on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y php
          sudo apt-get install -y composer
      - name: Composer install
        run: |
          composer install
      - name: Run tests
        run: |
          ./vendor/bin/phpunit ${{ matrix.test }}
