name: Test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        test: [
          tests/Mongodb503Test.php,
          tests/Mongodb4410Test.php,
          tests/Mysql5731Test.php,
          tests/Mysql8030Test.php,
          tests/Postgresql124Test.php,
          tests/Postgresql132Test.php,
          tests/Redis626Test.php,
          tests/Redis6016Test.php,
          tests/Memcached1631Test.php
        ]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Composer dependencies
        run: composer install
      - name: Run tests
        run: ./vendor/bin/phpunit ${{ matrix.test }}
